# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e852d7f3894e567b98eb8bdd314dd7c147a0c71f60d323b9a15fd0738b52efc7148b8c681807f3e557ce01c482609b65c6966ce0186e771a5c9227889e055f

test:
  secret_key_base: ce766c5250960d54caa554fc4c5ae75a254e9795fd9fd2f1a70f7174f960cdacbfeb8ed870db72135658e30a1ff327d2c84c9f175d87d68acbea6b11e11f0183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
